#!/bin/sh
set -e

FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if echo "$FILES" | grep -q "^frontend/"; then
  FRONTEND_FILES=$(echo "$FILES" | sed -n 's#^frontend/##p')

  echo "Formatting staged frontend files..."
  (
    cd frontend
    echo "$FRONTEND_FILES" | xargs pnpm exec prettier --write --ignore-unknown
  )
  echo "$FILES" | grep "^frontend/" | xargs git add

  echo "Running frontend lint..."
  cd frontend
  pnpm run lint
fi
